const movie_list = [
  {"Title":"Tenet","Year":"2020","Rated":"PG-13","Released":"03 Sep 2020","Runtime":"150 min","Genre":"Action, Sci-Fi, Thriller","Director":"Christopher Nolan","Writer":"Christopher Nolan","Actors":"John David Washington, Robert Pattinson, Elizabeth Debicki","Plot":"Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.","Language":"English, Russian, Ukrainian, Estonian, Norwegian, Hindi","Country":"United States, United Kingdom","Awards":"Won 1 Oscar. 44 wins & 136 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BYzg0NGM2NjAtNmIxOC00MDJmLTg5ZmYtYzM0MTE4NWE2NzlhXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.4/10"},{"Source":"Rotten Tomatoes","Value":"70%"},{"Source":"Metacritic","Value":"69/100"}],"Metascore":"69","imdbRating":"7.4","imdbVotes":"428,564","imdbID":"tt6723592","Type":"movie","DVD":"15 Dec 2020","BoxOffice":"$58,456,624","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Dunkirk","Year":"2017","Rated":"PG-13","Released":"21 Jul 2017","Runtime":"106 min","Genre":"Action, Drama, History","Director":"Christopher Nolan","Writer":"Christopher Nolan","Actors":"Fionn Whitehead, Barry Keoghan, Mark Rylance","Plot":"Allied soldiers from Belgium, the British Commonwealth and Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.","Language":"English, French, German","Country":"United Kingdom, Netherlands, France, United States","Awards":"Won 3 Oscars. 63 wins & 230 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BN2YyZjQ0NTEtNzU5MS00NGZkLTg0MTEtYzJmMWY3MWRhZjM2XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.8/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"94/100"}],"Metascore":"94","imdbRating":"7.8","imdbVotes":"598,930","imdbID":"tt5013056","Type":"movie","DVD":"12 Dec 2017","BoxOffice":"$189,740,665","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Interstellar","Year":"2014","Rated":"PG-13","Released":"07 Nov 2014","Runtime":"169 min","Genre":"Adventure, Drama, Sci-Fi","Director":"Christopher Nolan","Writer":"Jonathan Nolan, Christopher Nolan","Actors":"Matthew McConaughey, Anne Hathaway, Jessica Chastain","Plot":"A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.","Language":"English","Country":"United Kingdom, Canada, United States","Awards":"Won 1 Oscar. 44 wins & 148 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"72%"},{"Source":"Metacritic","Value":"74/100"}],"Metascore":"74","imdbRating":"8.6","imdbVotes":"1,625,316","imdbID":"tt0816692","Type":"movie","DVD":"31 Mar 2015","BoxOffice":"$188,020,017","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"The Dark Knight Rises","Year":"2012","Rated":"PG-13","Released":"20 Jul 2012","Runtime":"164 min","Genre":"Action","Director":"Christopher Nolan","Writer":"Jonathan Nolan, Christopher Nolan, David S. Goyer","Actors":"Christian Bale, Tom Hardy, Anne Hathaway","Plot":"Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.","Language":"English, Arabic","Country":"United Kingdom, United States","Awards":"38 wins & 103 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"78/100"}],"Metascore":"78","imdbRating":"8.4","imdbVotes":"1,580,855","imdbID":"tt1345836","Type":"movie","DVD":"04 Dec 2012","BoxOffice":"$448,139,099","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Inception","Year":"2010","Rated":"PG-13","Released":"16 Jul 2010","Runtime":"148 min","Genre":"Action, Adventure, Sci-Fi","Director":"Christopher Nolan","Writer":"Christopher Nolan","Actors":"Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page","Plot":"A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.","Language":"English, Japanese, French","Country":"United Kingdom, United States","Awards":"Won 4 Oscars. 157 wins & 220 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.8/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"74/100"}],"Metascore":"74","imdbRating":"8.8","imdbVotes":"2,179,906","imdbID":"tt1375666","Type":"movie","DVD":"07 Dec 2010","BoxOffice":"$292,576,195","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"The Dark Knight","Year":"2008","Rated":"PG-13","Released":"18 Jul 2008","Runtime":"152 min","Genre":"Action, Crime, Drama","Director":"Christopher Nolan","Writer":"Jonathan Nolan, Christopher Nolan, David S. Goyer","Actors":"Christian Bale, Heath Ledger, Aaron Eckhart","Plot":"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.","Language":"English, Mandarin","Country":"United States, United Kingdom","Awards":"Won 2 Oscars. 159 wins & 163 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.0/10"},{"Source":"Rotten Tomatoes","Value":"94%"},{"Source":"Metacritic","Value":"84/100"}],"Metascore":"84","imdbRating":"9.0","imdbVotes":"2,429,262","imdbID":"tt0468569","Type":"movie","DVD":"09 Dec 2008","BoxOffice":"$534,858,444","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"The Prestige","Year":"2006","Rated":"PG-13","Released":"20 Oct 2006","Runtime":"130 min","Genre":"Drama, Mystery, Sci-Fi","Director":"Christopher Nolan","Writer":"Jonathan Nolan, Christopher Nolan, Christopher Priest","Actors":"Christian Bale, Hugh Jackman, Scarlett Johansson","Plot":"After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.","Language":"English","Country":"United Kingdom, United States","Awards":"Nominated for 2 Oscars. 6 wins & 45 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"76%"},{"Source":"Metacritic","Value":"66/100"}],"Metascore":"66","imdbRating":"8.5","imdbVotes":"1,247,611","imdbID":"tt0482571","Type":"movie","DVD":"13 Feb 2007","BoxOffice":"$53,089,891","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Batman Begins","Year":"2005","Rated":"PG-13","Released":"15 Jun 2005","Runtime":"140 min","Genre":"Action, Adventure","Director":"Christopher Nolan","Writer":"Bob Kane, David S. Goyer, Christopher Nolan","Actors":"Christian Bale, Michael Caine, Ken Watanabe","Plot":"After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.","Language":"English, Mandarin","Country":"United Kingdom, United States","Awards":"Nominated for 1 Oscar. 13 wins & 79 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.2/10"},{"Source":"Rotten Tomatoes","Value":"84%"},{"Source":"Metacritic","Value":"70/100"}],"Metascore":"70","imdbRating":"8.2","imdbVotes":"1,362,365","imdbID":"tt0372784","Type":"movie","DVD":"18 Oct 2005","BoxOffice":"$206,852,432","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Insomnia","Year":"2002","Rated":"R","Released":"24 May 2002","Runtime":"118 min","Genre":"Drama, Mystery, Thriller","Director":"Christopher Nolan","Writer":"Hillary Seitz, Nikolaj Frobenius, Erik Skjoldbjærg","Actors":"Al Pacino, Robin Williams, Hilary Swank","Plot":"Two Los Angeles homicide detectives are dispatched to a northern town where the sun doesn't set to investigate the methodical murder of a local teen.","Language":"English","Country":"United States, United Kingdom","Awards":"1 win & 11 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BYzlkZTEyYjUtMTY5NS00ZjU0LTk5OTYtM2M0ZDg1NmNjMzhkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.2/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"78/100"}],"Metascore":"78","imdbRating":"7.2","imdbVotes":"284,847","imdbID":"tt0278504","Type":"movie","DVD":"15 Oct 2002","BoxOffice":"$67,355,513","Production":"N/A","Website":"N/A","Response":"True"},
  {"Title":"Memento","Year":"2000","Rated":"R","Released":"25 May 2001","Runtime":"113 min","Genre":"Mystery, Thriller","Director":"Christopher Nolan","Writer":"Christopher Nolan, Jonathan Nolan","Actors":"Guy Pearce, Carrie-Anne Moss, Joe Pantoliano","Plot":"A man with short-term memory loss attempts to track down his wife's murderer.","Language":"English","Country":"United States","Awards":"Nominated for 2 Oscars. 57 wins & 59 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"93%"},{"Source":"Metacritic","Value":"80/100"}],"Metascore":"80","imdbRating":"8.4","imdbVotes":"1,172,676","imdbID":"tt0209144","Type":"movie","DVD":"04 Sep 2001","BoxOffice":"$25,544,867","Production":"N/A","Website":"N/A","Response":"True"}
];

function fillElements(index){
  // Append list of ID's with the movie index
  let ids = ["poster", "title", "rating", "year", "plot"]
  for (let i=0; i<5; i++){
    ids[i] = ids[i] + String(index)
  }

  // Insert the poster and title
  document.getElementById(ids[0]).src = movie_list[index].Poster;
  document.getElementById(ids[1]).innerHTML = movie_list[index].Title;

  // Find the Rotten Tomatoes rating and insert it to the document
  for (let ratings of movie_list[index].Ratings){
    if (ratings.Source === "Rotten Tomatoes"){
      document.getElementById(ids[2]).innerHTML = ratings.Value
    }
  };

  // Insert the year and plot
  document.getElementById(ids[3]).innerHTML = movie_list[index].Year;
  document.getElementById(ids[4]).innerHTML = movie_list[index].Plot;
};